name: 'Setup Windows'
description: 'Setup Windows'
runs:
  using: "composite"
  steps:
    - name: Install Windows dependencies
      shell: bash
      run: |
        set -v
        set -e
        choco install -y ninja wget ccache
        wget https://github.com/dokan-dev/dokany/releases/download/v2.0.6.1000/Dokan_x64.msi
        if [ $(sha512sum Dokan_x64.msi | awk '{print $1;}') == "761b4c9f354f9e540645947e135e84e9f30cbf527ca72a49bfb74cf9be022fae185ce9bbd5214bbfde929e12d8f5be0e57e13b09a4b18e706761fc5b2b856a61" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum Dokan_x64.msi
          exit 1
        fi
        echo Installing DokanY
        msiexec "-i" "Dokan_x64.msi" "-norestart" "-passive" INSTALLDEVFILES=1
        # msiexec "-i" "Dokan_x64.msi" "-norestart" "-passive" "-lv*!" dokan-install-logfile.txt INSTALLDEVFILES=1
        # cat dokan-install-logfile.txt
        echo Installing DokanY finished
