name: 'Setup macOS'
description: 'Setup macOS'
inputs:
  extra_homebrew_packages:
    description: "Job-specific homebrew packages to install (e.g. the compiler)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install macOS dependencies
      shell: bash
      run: |
        brew install coreutils ninja macfuse libomp ccache pkg-config ${{inputs.extra_homebrew_packages}}
