[package]
name = "cryfs-cli"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[[bin]]
name = "cryfs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap = {workspace = true, features = ["derive"]}
cryfs-blobstore = {path = "../blobstore"}
cryfs-blockstore = {path = "../blockstore"}
cryfs-cryfs = {path = "../cryfs"}
cryfs-rustfs = {path = "../rustfs", features = ["fuser"]}
cryfs-utils = {path = "../utils"}
cryfs-version = {path = "../cryfs-version"}
dialoguer.workspace = true
dirs.workspace = true
env_logger.workspace = true
path-absolutize.workspace = true
rpassword.workspace = true
tokio = {workspace = true, features = ["rt-multi-thread", "macros"]}

[dev-dependencies]
assert_cmd.workspace = true
envtestkit.workspace = true
escargot.workspace = true
lazy_static.workspace = true
pathdiff.workspace = true
predicates.workspace = true
tempdir.workspace = true

[features]
default = ["check_for_updates"]
check_for_updates = []
