[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-cryfs"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.68"
async-trait = "^0.1.60"
binary-layout = "^3.1.3"
binrw = "^0.11.1"
cryfs-blobstore = {path = "../blobstore"}
cryfs-blockstore = {path = "../blockstore"}
cryfs-utils = {path = "../utils"}
derive_more = "^0.99.17"
futures = "^0.3.25"
thiserror = "^1.0.38"
serde = {version = "^1.0.163", features=["derive"]}
serde_json = "^1.0.96"
serde_with = {version = "^3.0.0", features=["hex"]}
rand = "^0.8.5"
version-compare = "^0.1.1"
log = "^0.4.17"
hex = "^0.4.3"

[dev-dependencies]
tokio = {version = "^1.23.0", features = ["rt-multi-thread", "macros"]}
lockable = "^0.0.6"