name: 'Test'
description: 'Run CryFS Tests'
inputs:
  build_type:
    description: "Which cmake build type was used to build (e.g. Release, Debug, RelWithDebInfo)"
    required: true
  gtest_args:
    description: "Extra arguments for gtest runners, for example tests to exclude"
    required: true
  extra_env_vars:
    description: "Extra environment variables to set before running tests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        set -v
        set -e
        echo Running on ${{runner.os}}
        cd build/${{inputs.build_type}}/test

        export ${{ inputs.extra_env_vars }}

        ./gitversion/gitversion-test ${{inputs.gtest_args}}
        ./cpp-utils/cpp-utils-test ${{inputs.gtest_args}}
        ./parallelaccessstore/parallelaccessstore-test ${{inputs.gtest_args}}
        ./blockstore/blockstore-test ${{inputs.gtest_args}}
        ./blobstore/blobstore-test ${{inputs.gtest_args}}
        ./cryfs/cryfs-test ${{inputs.gtest_args}}

        # TODO Also run on macOS once fixed
        if [[ "${{runner.os}}" == "macOS" ]]; then
          echo Skipping some tests because they are not fixed for macOS yet
        else
          # TODO Also run with TSAN once fixed
          if [[ "${{matrix.name}}" != "TSAN" ]]; then
            ./fspp/fspp-test ${{inputs.gtest_args}}
          fi
          ./cryfs-cli/cryfs-cli-test ${{inputs.gtest_args}}
        fi
