[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-blobstore"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.68"
async-recursion = "^1.0.0"
async-trait = "^0.1.60"
binary-layout = "^3.1.3"
binrw = "^0.11.1"
conv = "^0.3.3"
cryfs-blockstore = {path = "../blockstore"}
cryfs-utils = {path = "../utils"}
divrem = "^1.0.0"
futures = "^0.3.25"

[dev-dependencies]
cryfs-blockstore = {path = "../blockstore", features = ["testutils"]}
cryfs-utils = {path = "../utils", features = ["testutils"]}
rand = {version = "^0.8.5", features = ["small_rng"]}
tokio = {version = "^1.23.0", features = ["macros"]}
iter-chunks = "^0.1.3"
rstest = "^0.16.0"
rstest_reuse = "^0.5.0"

[features]
# Enable tests that are very slow to build or run
# TODO We need a better way of doing this, see https://github.com/la10736/rstest/issues/184
slow-tests-any = []
slow-tests-1 = ["slow-tests-any"]
slow-tests-2 = ["slow-tests-any"]
slow-tests-3 = ["slow-tests-any"]
slow-tests-4 = ["slow-tests-any"]
slow-tests-5 = ["slow-tests-any"]
slow-tests-6 = ["slow-tests-any"]
