name: 'Show ccache statistics'
description: 'Show ccache statistics'
runs:
  using: "composite"
  steps:
    - name: Show ccache statistics
      if: ${{ runner.os == 'macOS' || runner.os == 'Windows'}}
      shell: bash
      run: |
        set -e
        set -v
        ccache -sv
    - name: Show ccache statistics
      if: ${{ runner.os != 'macOS' && runner.os != 'Windows'}}
      shell: bash
      run: |
        set -e
        set -v
        ccache -s
