name: 'Install local dependencies'
description: 'Install local dependencies'
runs:
  using: "composite"
  steps:
    - name: Install local dependencies
      shell: bash
      run: |
        set -v
        set -e
        # TODO Cache these dependencies for faster runtime

        export NUMCORES=`nproc` && if [ ! -n "$NUMCORES" ]; then export NUMCORES=`sysctl -n hw.ncpu`; fi
        echo Using $NUMCORES cores

        echo Download range-v3
        cd ~
        wget https://github.com/ericniebler/range-v3/archive/0.12.0.tar.gz -O range-v3-0.12.0.tar.gz
        if [ $(sha512sum range-v3-0.12.0.tar.gz | awk '{print $1;}') == "b8b632b8e0f2a3234ef61813212c237f648cd741e816ca57bd86f82f6459f7d755e2b70361d2aa43847874fb546a31a792ab1c3ba90292818ae7313438dc62d0" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum range-v3-0.12.0.tar.gz
          exit 1
        fi
        tar -xvf range-v3-0.12.0.tar.gz
        cd range-v3-0.12.0/

        echo Install range-v3
        mkdir build
        cd build
        cmake .. -DRANGES_HAS_WERROR=off -DRANGE_V3_EXAMPLES=off -DRANGE_V3_TESTS=off
        make -j$NUMCORES
        sudo make install
        cd ~
        rm -rf range-v3-0.12.0
        rm range-v3-0.12.0.tar.gz

        echo Download spdlog
        cd ~
        wget https://github.com/gabime/spdlog/archive/refs/tags/v1.11.0.tar.gz -O spdlog.tar.gz
        if [ $(sha512sum spdlog.tar.gz | awk '{print $1;}') == "210f3135c7af3ec774ef9a5c77254ce172a44e2fa720bf590e1c9214782bf5c8140ff683403a85b585868bc308286fbdeb1c988e4ed1eb3c75975254ffe75412" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum spdlog.tar.gz
          exit 1
        fi
        tar -xvf spdlog.tar.gz
        rm spdlog.tar.gz
        cd spdlog-1.11.0

        echo Install spdlog
        mkdir build
        cd build
        cmake ..
        make -j$NUMCORES
        sudo make install

        echo Download boost
        cd ~
        wget -O boost.tar.bz2 https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.bz2
        if [ $(sha512sum boost.tar.bz2 | awk '{print $1;}') == "5dfeb35198bb096e46cf9e131ef0334cb95bc0bf09f343f291b860b112598b3c36111bd8c232439c401a2b2fb832fa0c399a8d5b96afc60bd359dff070154497" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum boost.tar.bz2
          exit 1
        fi
        echo Extracting boost
        tar -xf boost.tar.bz2
        rm boost.tar.bz2
        cd boost_1_84_0

        echo Install boost
        ./bootstrap.sh --with-libraries=filesystem,system,thread,chrono,program_options
        sudo ./b2 link=shared cxxflags=-fPIC --prefix=/usr -d0 -j$NUMCORES install
